In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

## 1. Tensor
n-dim array

In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
# şayet içeriği yazdırmak istiyorsak bunu bir Graph üzerinde ve session içinde çalıştırmalıyız.

In [8]:
# with ile çalışmamızın sebebi session açar blok içini çalıştırır ve session kapatır

with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World'


In [10]:
sess.run(hello+world)

RuntimeError: Attempted to use a closed Session.

In [10]:
# b nedir? bytes literal boş verin

In [11]:
a = tf.constant(10)
b = tf.constant(20)
a + b 

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [13]:
print(result)

30


In [14]:
const = tf.constant(10)

In [15]:
fill_mat = tf.fill((4,4), 10)

In [16]:
my_zeros = tf.zeros((4,4))

In [17]:
my_ones = tf.ones((4,4))

In [18]:
# normal dağılım
my_randn = tf.random_normal((4,4), mean=0.0, stddev=1.0)

In [19]:
# uniform dağılım
my_randu = tf.random_uniform((4,4), minval=0, maxval=1)

In [20]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_randn, my_randu]

## Interactive Session for Jupyter

In [21]:
# Bu parağraftan sonrakiler sess ile çalışacaktır.
sess = tf.InteractiveSession()

In [22]:
for op in my_ops:
    print(op)
    print(sess.run(op))
    print("\n")

Tensor("Const_4:0", shape=(), dtype=int32)
10


Tensor("Fill:0", shape=(4, 4), dtype=int32)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


Tensor("zeros:0", shape=(4, 4), dtype=float32)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Tensor("ones:0", shape=(4, 4), dtype=float32)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Tensor("random_normal:0", shape=(4, 4), dtype=float32)
[[-0.70241517  0.04583783 -0.67777586  1.4247029 ]
 [-0.16526307  0.6616756   0.551594    1.1495245 ]
 [-1.2781168   0.27131575 -0.5103622   0.14731546]
 [-1.0210792   0.25943178 -0.30880857 -0.9173592 ]]


Tensor("random_uniform:0", shape=(4, 4), dtype=float32)
[[0.25526214 0.637578   0.5806054  0.18772662]
 [0.8235315  0.13909745 0.14837861 0.1613903 ]
 [0.43869257 0.2976061  0.21418571 0.31326056]
 [0.39841902 0.90289474 0.5691048  0.4690101 ]]




In [23]:
#Ancak with tf.Session() as sess:
# kullanımı yaygındır. Sık sık bu şekilde karşımıza çıkar. 
# import pandas as pd gibi

## Matrix Multipication with Tensorflow

In [24]:
a = tf.constant([ [1,2],
                  [3,4]  ])

In [25]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [26]:
b = tf.constant([ [10], [100] ])

In [27]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [28]:
# boyutların uygun olmasına dikkat. 
# Birincinin sütun sayısı ikincinin satır sayısına eşit olmalı.
result = tf.matmul(a,b)

In [29]:
sess.run(result)

array([[210],
       [430]])